#!/usr/bin/env python

import sys
from math import sqrt, cos, sin, tan, asin, acos, atan, log, log10, pi


def main(argv):
    globs = {'sqrt': sqrt, 'cos': cos, 'sin': sin, 'tan': tan, 'asin': asin,
             'acos': acos, 'atan': atan, 'log': log, 'log10': log10, 'pi': pi}
    eq = ' '.join(argv)
    if not eq:
        print >> sys.stderr, "ERROR: Empty equation"
        return 1
    try:
        res = eval(eq, globs)
    except Exception, e:
        print >> sys.stderr, "ERROR: %s" % e
        return 1
    print >> sys.stdout, '%s = %s' % (eq, res)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))